In [1]:
import pandas as pd
import talib
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split  
from sklearn.naive_bayes import GaussianNB
import pandas_datareader as web
import datetime as dt

c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal


In [2]:
start = dt.datetime(1970,1,1).date()
end = pd.to_datetime("today").date()
company = "MSFT"
dataset = web.DataReader(company,"yahoo",start,end)

df=pd.DataFrame(dataset)

print('Newest Data:')
print(df.tail())
print('Earliest Data:')
print(df.head())

Newest Data:
                  High         Low        Open       Close      Volume  \
Date                                                                     
2020-05-21  186.669998  183.289993  185.399994  183.429993  29119500.0   
2020-05-22  184.460007  182.539993  183.190002  183.509995  20826900.0   
2020-05-26  186.500000  181.100006  186.339996  181.570007  36073600.0   
2020-05-27  181.990005  176.600006  180.199997  181.809998  39492600.0   
2020-05-28  184.139999  180.389999  180.740005  181.399994  31328190.0   

             Adj Close  
Date                    
2020-05-21  183.429993  
2020-05-22  183.509995  
2020-05-26  181.570007  
2020-05-27  181.809998  
2020-05-28  181.399994  
Earliest Data:
                High       Low      Open     Close        Volume  Adj Close
Date                                                                       
1986-03-13  0.101562  0.088542  0.088542  0.097222  1.031789e+09   0.062205
1986-03-14  0.102431  0.097222  0.097222  0.100694

In [3]:
high = np.array(df.High)
low = np.array(df.Low)
close = np.array(df.Close)
 
df['Today'] = df['Close']
df['pct change'] = df['Today'].pct_change()
df['Direction'] = np.sign(df['pct change'])


df['ADX'] = talib.ADX(high, low, close, timeperiod=14)
 
df['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
 
df['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
 
df['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
 
df['CCI'] = talib.CCI(high, low, close, timeperiod=14)
 
df['CMO'] = talib.CMO(close, timeperiod=14)
 
df['DX'] = talib.DX(high, low, close, timeperiod=14)
 
df['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
 
df['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
 
df['MOM'] = talib.MOM(close, timeperiod=10)
 
df['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
 
df['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
 
df['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
 
df['ROC'] = talib.ROC(close, timeperiod=10)
 
df['ROCP'] = talib.ROCP(close, timeperiod=10)
 
df['ROCR100'] = talib.ROCR100(close, timeperiod=10)
 
df['RSI'] = talib.RSI(close, timeperiod=14)
 
df['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
 
df['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)

# Added more

df['DEMA'] = talib.DEMA(close, timeperiod=30)

df['EMA'] = talib.EMA(close, timeperiod=30)

df['MA'] = talib.MA(close, timeperiod=30, matype=0)

df['SAR'] = talib.SAR(high, low, acceleration=0, maximum=0)

df['WMA'] = talib.WMA(close, timeperiod=30)

c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: invalid value encountered in sign
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [4]:
df.dropna(inplace = True)
df.tail()

High         Low        Open       Close      Volume  \
Date                                                                     
2020-05-21  186.669998  183.289993  185.399994  183.429993  29119500.0   
2020-05-22  184.460007  182.539993  183.190002  183.509995  20826900.0   
2020-05-26  186.500000  181.100006  186.339996  181.570007  36073600.0   
2020-05-27  181.990005  176.600006  180.199997  181.809998  39492600.0   
2020-05-28  184.139999  180.389999  180.740005  181.399994  31328190.0   

             Adj Close       Today  pct change  Direction        ADX  ...  \
Date                                                                  ...   
2020-05-21  183.429993  183.429993   -0.012011       -1.0  23.034254  ...   
2020-05-22  183.509995  183.509995    0.000436        1.0  22.840628  ...   
2020-05-26  181.570007  181.570007   -0.010572       -1.0  23.079300  ...   
2020-05-27  181.809998  181.809998    0.001322        1.0  21.960693  ...   
2020-05-28  181.399994  181.399994   -0.002255       -1.0  21.391984  ...   

                ROCP     ROCR100        RSI     ULTOSC      WILLR        DEMA  \
Date                                                                            
2020-05-21 -0.000926   99.907400  57.172533  54.122572 -29.759332  184.689560   
2020-05-22 -0.006335   99.366473  57.262764  54.059136 -33.812336  184.994995   
2020-05-26 -0.027686   97.231446  54.276497  43.889972 -50.211211  185.013864   
2020-05-27 -0.003835   99.616461  54.591974  47.228199 -48.182553  185.046009   
2020-05-28  0.009179  100.917938  53.907656  44.232905 -51.648349  185.009474   

                   EMA          MA       SAR         WMA  
Date                                                      
2020-05-21  177.188332  177.668333  0.088542  180.464688  
2020-05-22  177.596181  178.280667  0.088542  180.841570  
2020-05-26  177.852557  178.816000  0.088542  181.053785  
2020-05-27  178.107876  179.086334  0.088542  181.246946  
2020-05-28  178.320271  179.403667  0.088542  181.396215  

[5 rows x 33 columns]

In [5]:
df.drop(['High', 'Low', 'Close', 'Open', 'Close', 'Volume', 'Adj Close', 'Today', 'pct change'], axis = 1, inplace = True)
df.tail()

Direction        ADX       ADXR       APO   AROONOSC         CCI  \
Date                                                                           
2020-05-21       -1.0  23.034254  23.090339  4.435256  35.714286   53.876278   
2020-05-22        1.0  22.840628  23.103436  4.267243  35.714286    9.477605   
2020-05-26       -1.0  23.079300  23.363366  3.983846 -21.428571  -16.631188   
2020-05-27        1.0  21.960693  22.960378  3.485064 -21.428571 -126.216542   
2020-05-28       -1.0  21.391984  22.856015  2.517756 -21.428571  -43.835670   

                  CMO         DX   MINUS_DI   MINUS_DM  ...      ROCP  \
Date                                                    ...             
2020-05-21  14.345067  23.674336  15.680520  11.068343  ... -0.000926   
2020-05-22  14.525528  20.323491  16.345953  11.027747  ... -0.006335   
2020-05-26   8.552993  26.182026  15.048767  10.240051  ... -0.027686   
2020-05-27   9.183948   7.418800  20.428062  14.008618  ... -0.003835   
2020-05-28   7.815312  13.998772  19.291943  13.008003  ...  0.009179   

               ROCR100        RSI     ULTOSC      WILLR        DEMA  \
Date                                                                  
2020-05-21   99.907400  57.172533  54.122572 -29.759332  184.689560   
2020-05-22   99.366473  57.262764  54.059136 -33.812336  184.994995   
2020-05-26   97.231446  54.276497  43.889972 -50.211211  185.013864   
2020-05-27   99.616461  54.591974  47.228199 -48.182553  185.046009   
2020-05-28  100.917938  53.907656  44.232905 -51.648349  185.009474   

                   EMA          MA       SAR         WMA  
Date                                                      
2020-05-21  177.188332  177.668333  0.088542  180.464688  
2020-05-22  177.596181  178.280667  0.088542  180.841570  
2020-05-26  177.852557  178.816000  0.088542  181.053785  
2020-05-27  178.107876  179.086334  0.088542  181.246946  
2020-05-28  178.320271  179.403667  0.088542  181.396215  

[5 rows x 25 columns]

In [6]:
y = df['Direction']
x = df.drop('Direction', axis = 1)

In [7]:
split = 0.8
param = int(len(df)*split)

x_train = x[:param]
x_test = x[param:]
y_train = y[:param]
y_test = y[param:]

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

#####  KNN

In [9]:
from sklearn.metrics import confusion_matrix

model = KNeighborsClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of kNN model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of kNN model: 0.662
Confusion matrix: 
[[507   6 288]
 [  0   0   0]
 [275  10 627]]


In [10]:
model = KNeighborsClassifier(n_neighbors=25)
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of kNN model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of kNN model: 0.674
Confusion matrix: 
[[509   5 269]
 [  0   0   0]
 [273  11 646]]


##### Logistic Regression

In [11]:
model = LogisticRegression()
model.fit(x_train, y_train)

c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [12]:
pred = model.predict(x_test)

In [13]:
print("Accuracy of Logstic Regression model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of Logstic Regression model: 0.699
Confusion matrix: 
[[381   3  98]
 [  0   0   0]
 [401  13 817]]


In [14]:
model = LogisticRegression(C=4, penalty='l2')
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of Logstic Regression model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Accuracy of Logstic Regression model: 0.702
Confusion matrix: 
[[392   3 104]
 [  0   0   0]
 [390  13 811]]


##### SVM 
First I use the Linear Support Vector Machine Classifier however this performed the worst out of all the models so far. I changed it to the standard SVC model. I tuned the paramters until I got a more accurate model. 

In [15]:
model = LinearSVC()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of SVM model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of SVM model: 0.675
Confusion matrix: 
[[430   6 189]
 [  0   0   0]
 [352  10 726]]


c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [16]:
from sklearn.svm import SVC

model = SVC()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of SVM model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Accuracy of SVM model: 0.534
Confusion matrix: 
[[  0   0   0]
 [  0   0   0]
 [782  16 915]]


In [17]:
model = SVC(kernel="linear", C=0.025, random_state=101)
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of SVM model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of SVM model: 0.684
Confusion matrix: 
[[331   3  74]
 [  0   0   0]
 [451  13 841]]


##### Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_jobs=1,n_estimators=100,verbose=True,oob_score=True)
# try without n_jobs-1

clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("Accuracy of RF model: %0.3f" % clf.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Accuracy of RF model: 0.699
Confusion matrix: 
[[501   6 219]
 [  0   0   0]
 [281  10 696]]


[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


In [19]:
clf = RandomForestClassifier(n_estimators=70, oob_score=True, n_jobs=-1,
                            random_state=101, max_features=None, min_samples_leaf=30)
# try without n_jobs-1

clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("Accuracy of RF model: %0.3f" % clf.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of RF model: 0.717
Confusion matrix: 
[[519   5 206]
 [  0   0   0]
 [263  11 709]]


In [20]:
clf = RandomForestClassifier(n_estimators=200, criterion='entropy',max_features='auto')
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("Accuracy of RF model: %0.3f" % clf.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of RF model: 0.717
Confusion matrix: 
[[536   6 222]
 [  0   0   0]
 [246  10 693]]


##### Naives Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)
pred = nb.predict(x_test)
print("Accuracy of NB model: %0.3f" % nb.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of NB model: 0.601
Confusion matrix: 
[[522   6 408]
 [  0   0   0]
 [260  10 507]]


In [22]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(x_train, y_train)
pred = nb.predict(x_test)
print("Accuracy of NB model: %0.3f" % nb.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of NB model: 0.588
Confusion matrix: 
[[358   5 266]
 [  0   0   0]
 [424  11 649]]


##### Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(max_depth=10, random_state=101, max_features=None, min_samples_leaf=15)
dtree.fit(x_train, y_train)
pred = dtree.predict(x_test)
print("Accuracy of DT model: %0.3f" % dtree.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of DT model: 0.668
Confusion matrix: 
[[472   6 242]
 [  0   0   0]
 [310  10 673]]


In [24]:
dtree = DecisionTreeClassifier(criterion='gini', max_depth=3, min_samples_leaf=6)
dtree.fit(x_train, y_train)
pred = dtree.predict(x_test)
print("Accuracy of DT model: %0.3f" % dtree.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of DT model: 0.661
Confusion matrix: 
[[524   6 306]
 [  0   0   0]
 [258  10 609]]


##### XGBOOST

In [25]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of XBG model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

Accuracy of XBG model: 0.712
Confusion matrix: 
[[522   8 217]
 [  0   0   0]
 [260   8 698]]
              precision    recall  f1-score   support

        -1.0       0.70      0.67      0.68       782
         0.0       0.00      0.00      0.00        16
         1.0       0.72      0.76      0.74       915

   micro avg       0.71      0.71      0.71      1713
   macro avg       0.47      0.48      0.47      1713
weighted avg       0.70      0.71      0.71      1713



c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


##### Stochastic Gradient Descent

In [26]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss='modified_huber', shuffle=True, random_state=101)
sgd.fit(x_train, y_train)
pred = sgd.predict(x_test)
print("Accuracy of SGD model: %0.3f" % sgd.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of SGD model: 0.508
Confusion matrix: 
[[768  16 813]
 [  0   0   0]
 [ 14   0 102]]


c:\users\hayes\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


##### LightGBM

In [27]:
from lightgbm import LGBMClassifier
model = LGBMClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Accuracy of SGD model: %0.3f" % model.score(x_test, y_test))
print("Confusion matrix: \n%s" % confusion_matrix(pred, y_test))

Accuracy of SGD model: 0.726
Confusion matrix: 
[[557   9 228]
 [  0   0   0]
 [225   7 687]]


##### Best 
Random Forest, Logistic Regression, XGBoost, LightGBM